### ISSUE TITLE
Inline rules and inline motions

### ISSUE THREAD

**Issue by dixonary** [samcoy3/rdan#1]
The ability to type, for example, `!r20` or `!m20` inline would be convenient for referring to rules.

It would also be great if it could pull out and print more than one at once, for example

```
I think !r10 conflicts with !r11 here.
```

would print both the text of rule 10 and rule 11.

**Comment by samcoy3** [comment]
Merged with commit https://github.com/samcoy3/rdan/commit/5659bfb7d81e1abe7f27ad79661e0bbd842c1710.
